// <auto-generated />
using System;
using ErisCakesWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErisCakesWebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ErisCakesWebApi.Models.BakeryRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BakeryRecipes", (string)null);
                });

            modelBuilder.Entity("ErisCakesWebApi.Models.BakeryRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BillingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EstimateDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("EstimatedPrice")
                        .HasColumnType("float");

                    b.Property<int>("JobScore")
                        .HasColumnType("int");

                    b.Property<string>("RecipeStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("BakeryRequests", (string)null);
                });

            modelBuilder.Entity("ErisCakesWebApi.Models.BakeryRequestRecipe", b =>
                {
                    b.Property<int>("BakeryRequestId")
                        .HasColumnType("int");

                    b.Property<int>("BakeryRecipeId")
                        .HasColumnType("int");

                    b.HasKey("BakeryRequestId", "BakeryRecipeId");

                    b.HasIndex("BakeryRecipeId");

                    b.ToTable("BakeryRequestRecipes", (string)null);
                });

            modelBuilder.Entity("ErisCakesWebApi.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("ErisCakesWebApi.Models.BakeryRequest", b =>
                {
                    b.HasOne("ErisCakesWebApi.Models.Client", "Client")
                        .WithMany("BakeryRequests")
                        .HasForeignKey("ClientId")
                        .HasConstraintName("FK_BakeryRequest_Client");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ErisCakesWebApi.Models.BakeryRequestRecipe", b =>
                {
                    b.HasOne("ErisCakesWebApi.Models.BakeryRecipe", "BakeryRecipe")
                        .WithMany("BakeryRequestRecipes")
                        .HasForeignKey("BakeryRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BakeryRequestRecipe_BakeryRecipe");

                    b.HasOne("ErisCakesWebApi.Models.BakeryRequest", "BakeryRequest")
                        .WithMany("BakeryRequestRecipes")
                        .HasForeignKey("BakeryRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BakeryRequestRecipe_BakeryRequest");

                    b.Navigation("BakeryRecipe");

                    b.Navigation("BakeryRequest");
                });

            modelBuilder.Entity("ErisCakesWebApi.Models.BakeryRecipe", b =>
                {
                    b.Navigation("BakeryRequestRecipes");
                });

            modelBuilder.Entity("ErisCakesWebApi.Models.BakeryRequest", b =>
                {
                    b.Navigation("BakeryRequestRecipes");
                });

            modelBuilder.Entity("ErisCakesWebApi.Models.Client", b =>
                {
                    b.Navigation("BakeryRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
